# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abinav Ravi Venkatakrishnan
email: abinav.rvkrish@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Machine Learning operations, Software Engg for Machine Learning
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

collections:
    drafts:
        output: true
        permalink: /:collection/:name/
    notes:
        output: true
        permalink: /:collection/:name/

defaults:
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: draft


twitter_username: AbinavRavi
github_username:  AbinavRavi
linkedin_username: abinav-ravi-venkatakrishnan

# Build settings
markdown: kramdown
